CREATE TABLE "balance_fonts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "balance_by_fonts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "balance_font_id" integer,
  "balance" float,
  "created_at" timestamptz
);

CREATE TABLE "entry_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "entry_labels" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "color" varchar,
  "entry_id" integer,
  "entry_type_id" integer
);

CREATE TABLE "entries" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "value" float,
  "entry_type_id" integer,
  "created_at" timestamptz
);

ALTER TABLE "balance_by_fonts" ADD FOREIGN KEY ("balance_font_id") REFERENCES "balance_fonts" ("id");

ALTER TABLE "entry_labels" ADD FOREIGN KEY ("entry_id") REFERENCES "entries" ("id");

ALTER TABLE "entry_labels" ADD FOREIGN KEY ("entry_type_id") REFERENCES "entry_type" ("id");

ALTER TABLE "entries" ADD FOREIGN KEY ("entry_type_id") REFERENCES "entry_type" ("id");
